// GENERAL block
int run ;
int event ;
float ecm ;
float xangle ;
float eneu ;
float echg ;
float evtmm2 ;
int l1trig ;
int nbunch ;
int bunch ;
int l1trig2 ;
float pxcm ;
float pycm ;
float pzcm ;
// TRACK block
int ntrack ;
#define MAXNTRACK 100
int trident[MAXNTRACK] ;
float trpie[MAXNTRACK] ;
float trpipx[MAXNTRACK] ;
float trpipy[MAXNTRACK] ;
float trpipz[MAXNTRACK] ;
float trpip[MAXNTRACK] ;
float trke[MAXNTRACK] ;
float trkpx[MAXNTRACK] ;
float trkpy[MAXNTRACK] ;
float trkpz[MAXNTRACK] ;
float trchg[MAXNTRACK] ;
float trz0[MAXNTRACK] ;
float trd0[MAXNTRACK] ;
float trcosth[MAXNTRACK] ;
float trphi0[MAXNTRACK] ;
float trdrhitf[MAXNTRACK] ;
float trzdhitf[MAXNTRACK] ;
float trhitf[MAXNTRACK] ;
float trchi2[MAXNTRACK] ;
int trchi2dof[MAXNTRACK] ;
float trsigpi[MAXNTRACK] ;
float trsigk[MAXNTRACK] ;
float trrichpll[MAXNTRACK] ;
int trrichpnp[MAXNTRACK] ;
float trrichkll[MAXNTRACK] ;
int trrichknp[MAXNTRACK] ;
int trtaginfo[MAXNTRACK] ;
int trfabort[MAXNTRACK] ;
int trrichphp[MAXNTRACK] ;
int trrichkhp[MAXNTRACK] ;
float trdb[MAXNTRACK] ;
float trdpthmu[MAXNTRACK] ;
float trroceid[MAXNTRACK] ;
int trtrkman[MAXNTRACK] ;
// SHOWER block
int nshow ;
#define MAXNSHOW 1000
int sident[MAXNSHOW] ;
float se[MAXNSHOW] ;
float spx[MAXNSHOW] ;
float spy[MAXNSHOW] ;
float spz[MAXNSHOW] ;
float sphi[MAXNSHOW] ;
float scosth[MAXNSHOW] ;
int se9o25uok[MAXNSHOW] ;
int shot[MAXNSHOW] ;
int sdettype[MAXNSHOW] ;
int strmatch[MAXNSHOW] ;
float strme[MAXNSHOW] ;
float strdist[MAXNSHOW] ;
float se9o25[MAXNSHOW] ;
float se9o25u[MAXNSHOW] ;
// PI0 block
int npi0 ;
#define MAXNPI0 1000
int pi0ident[MAXNPI0] ;
float pi0mass[MAXNPI0] ;
float pi0chi2[MAXNPI0] ;
float pi0e[MAXNPI0] ;
float pi0px[MAXNPI0] ;
float pi0py[MAXNPI0] ;
float pi0pz[MAXNPI0] ;
float pi0merr[MAXNPI0] ;
int pi0dau1[MAXNPI0] ;
int pi0dau2[MAXNPI0] ;
int pi0istype1[MAXNPI0] ;
// ETA block
int neta ;
#define MAXNETA 1000
int etaident[MAXNETA] ;
float etamass[MAXNETA] ;
float etachi2[MAXNETA] ;
float etae[MAXNETA] ;
float etapx[MAXNETA] ;
float etapy[MAXNETA] ;
float etapz[MAXNETA] ;
float etamerr[MAXNETA] ;
int etadau1[MAXNETA] ;
int etadau2[MAXNETA] ;
// KSHORT block
int nks ;
#define MAXNKS 50
int ksident[MAXNKS] ;
float ksmass[MAXNKS] ;
float kse[MAXNKS] ;
float kspx[MAXNKS] ;
float kspy[MAXNKS] ;
float kspz[MAXNKS] ;
float kschi2[MAXNKS] ;
float ksrad[MAXNKS] ;
float ksraderr[MAXNKS] ;
int ksdau1[MAXNKS] ;
int ksdau2[MAXNKS] ;
float ksflsig[MAXNKS] ;
// DTAG block
int ndcand ;
#define MAXNDCAND 1000
int dmode[MAXNDCAND] ;
float dmbc[MAXNDCAND] ;
float ddeltae[MAXNDCAND] ;
float ddeltaeerr[MAXNDCAND] ;
float dmraw[MAXNDCAND] ;
float dmrawerr[MAXNDCAND] ;
float dkchi2[MAXNDCAND] ;
float de[MAXNDCAND] ;
float dpx[MAXNDCAND] ;
float dpy[MAXNDCAND] ;
float dpz[MAXNDCAND] ;
int ddau1[MAXNDCAND] ;
int ddau2[MAXNDCAND] ;
int ddau3[MAXNDCAND] ;
int ddau4[MAXNDCAND] ;
int dcsign[MAXNDCAND] ;
int lepveto[MAXNDCAND] ;
int ddau5[MAXNDCAND] ;
// MMISS block
int nmiss ;
#define MAXNMISS 10000
int mmode[MAXNMISS] ;
int mdcand[MAXNMISS] ;
int mtrack1[MAXNMISS] ;
int mtrack2[MAXNMISS] ;
float mmsq[MAXNMISS] ;
float mpx[MAXNMISS] ;
float mpy[MAXNMISS] ;
float mpz[MAXNMISS] ;
float me[MAXNMISS] ;
float mbestmbc[MAXNMISS] ;
// DDOUBLETAG block
int nddcand ;
#define MAXNDDCAND 200
int d[MAXNDDCAND] ;
int dbar[MAXNDDCAND] ;
int ddmode[MAXNDDCAND] ;
float cosangle[MAXNDDCAND] ;
float chi2vd[MAXNDDCAND] ;
float chi2vdb[MAXNDDCAND] ;
float chi2ed[MAXNDDCAND] ;
float chi2edb[MAXNDDCAND] ;
float chi2md[MAXNDDCAND] ;
float chi2mdb[MAXNDDCAND] ;
float chi2vddb[MAXNDDCAND] ;
// MC block
int mcdmode ;
int mcdbmode ;
int mcdmatch[MAXNDCAND] ;
int nmcpart ;
#define MAXNMCPART 50
int mcident[MAXNMCPART] ;
int mcpdgid[MAXNMCPART] ;
int mcparent[MAXNMCPART] ;
float mce[MAXNMCPART] ;
float mcpx[MAXNMCPART] ;
float mcpy[MAXNMCPART] ;
float mcpz[MAXNMCPART] ;
int mctruth[MAXNMCPART] ;
int end_marker ;
