#if !defined(_REPLACE_BY_PROCDIR___REPLACE_BY_TUPLENAME__H)
#define _REPLACE_BY_PROCDIR___REPLACE_BY_TUPLENAME__H

// -*- C++ -*-
//
// Package:     _REPLACE_BY_PROCDIR_
// Module:	_REPLACE_BY_TUPLENAME_
//
// Description: Autogenerated tuple class
//
// Usage:
//      [class and public member function
//       documentation goes here]
//
// Author:      A. Trackfinder
// Created:     Thu Jan  1 00:00:01 EST 1996
// $Id$
//
// Revision history
//
// $Log$
// Revision 1.1  2010/05/17 17:43:51  xs32
// add
//
// Revision 1.1.1.1  2004/09/24 16:41:30  ponyisi
// import CWNFramework
//


#include "CWNFramework/CWNTuple.h"

class _REPLACE_BY_TUPLENAME_ : public CWNTuple {
  public:
   _REPLACE_BY_TUPLENAME_();
   void clear();

#include "_REPLACE_BY_PROCDIR_/tuple_cxx_structure.h"

};

#endif /* _REPLACE_BY_PROCDIR___REPLACE_BY_TUPLENAME__H */
